FROM elixir:1.10.2-alpine

ARG MIX_ENV=dev
ENV MIX_ENV=${MIX_ENV}

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

COPY lib lib
COPY config config
COPY priv priv

COPY mix.exs ./
COPY mix.lock ./

RUN mix deps.get

CMD ["mix", "ecto.reset"]
